[project]
name = "customer-churn-mlops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "apache-airflow>=3.1.0",
    "apache-airflow-providers-docker>=4.4.4",
    "black[jupyter]>=25.9.0",
    "docker>=7.1.0",
    "fastapi[standard]>=0.119.1",
    "feast>=0.1.2.post1",
    "isort>=7.0.0",
    "loguru>=0.7.3",
    "matplotlib>=3.10.7",
    "mlflow>=3.5.1",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "psycopg2>=2.9.11",
    "pyarrow>=21.0.0",
    "pydantic>=2.12.3",
    "pydantic-settings>=2.11.0",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "xgboost>=3.0.5",
]
