global:
  scrape_interval: 15s  # How often to scrape targets by default
  evaluation_interval: 15s # How often to evaluate rules

scrape_configs:
  - job_name: 'fastapi_churn_service'
    scrape_interval: 5s # Scrape more frequently for real-time app metrics
    metrics_path: '/metrics'
    static_configs:
      - targets: ['fastapi_server:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']