global:
  scrape_interval: 15s  # How often to scrape targets by default
  evaluation_interval: 15s # How often to evaluate rules

scrape_configs:
  - job_name: 'churn_service'
    static_configs:
      - targets: ['fastapi_blue:8000', 'fastapi_green:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']