apiVersion: 1

datasources:
  # 1. Prometheus (Metrics)
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true 
    editable: false

  # 2. PostgreSQL (Prediction Logs)
  - name: PostgreSQL
    type: postgres
    uid: postgres
    access: proxy
    url: app_postgres:5432
    user: ${APP_DB_USER}
    database: ${APP_DB_NAME} 
    jsonData:
      sslmode: "disable"
      postgresVersion: 1300
    secureJsonData:
      password: ${APP_DB_PASSWORD}