apiVersion: 1

datasources:
  - name: app-datasource
    type: postgres
    url: app_postgres:5432
    user: ${APP_DB_USER}
    database: ${APP_DB_NAME}
    jsonData:
      sslmode: 'disable'
    secureJsonData:
      password: ${APP_DB_PASSWORD}

  - name: mlflow-datasource
    type: postgres
    url: mlflow_postgres:5432
    user: ${MLFLOW_DB_USER}
    database: ${MLFLOW_DB_NAME}
    jsonData:
      sslmode: 'disable'
    secureJsonData:
      password: ${MLFLOW_DB_PASSWORD}