{
 "title": "Base",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Spend Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "churn",
     "rawSql": "SELECT\n  $__timeGroup(timestamp, '1h') AS time,\n  AVG(total_spend) AS \"avg_total_spend\",\n  MIN(total_spend) AS \"min_total_spend\",\n  MAX(total_spend) AS \"max_total_spend\"\nFROM prediction_logs\nWHERE $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  { "title": "Predictions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Prediction Distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "dataset": "churn",
     "rawSql": "SELECT \n  prediction::text AS \"Churn Prediction\",\n  COUNT(*) AS \"count\"\nFROM prediction_logs\nWHERE $__timeFilter(timestamp)\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Prediction Probability Distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "churn",
     "rawSql": "SELECT\n  probability  -- Just select the raw probability\nFROM prediction_logs\nWHERE $__timeFilter(timestamp)"
    }
   ]
  },
  { "title": "Performances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Model Performance Overtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "mlflow",
     "rawSql": "SELECT \n  to_timestamp(m.timestamp / 1000) AS time,\n  r.run_uuid,\n  MAX(CASE WHEN m.key = 'f1_score' THEN m.value ELSE NULL END) AS \"f1_score\",\n  MAX(CASE WHEN m.key = 'accuracy' THEN m.value ELSE NULL END) AS \"accuracy\",\n  MAX(CASE WHEN m.key = 'roc_auc_curve' THEN m.value ELSE NULL END) AS \"roc_auc_curve\"\nFROM metrics m\nJOIN runs r ON m.run_uuid = r.run_uuid\nWHERE m.key IN ('f1_score', 'accuracy', 'roc_auc_curve')\nGROUP BY time, r.run_uuid\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "API Latency Overtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "dataset": "churn",
     "rawSql": "SELECT\n  $__timeGroup(timestamp, '5m') AS time,\n  PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY response_time_ms) AS \"p95_latency_ms\"\nFROM prediction_logs\nWHERE $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  }
 ]
}